### PR TITLE
Possibility to use custom scope

### PR DESCRIPTION
**Pull request by AndrzejKaczynski**
Hello.
I have added possibility to use custom scope while authenticating with slack.

I find this package to be amazing but it might be useful that people can add more scopes while getting slack token. For example I needed to get 'identity.avatar' as well to get user picture.

Let me know what do you think about it.

Cheers,
Andrzej :)

### CODE REVIEW

**Review by thomas-stockx — APPROVED** [review]
Looks great, thanks for your PR! I'll publish a new version on pub on Monday.

Have a nice weekend!

**Comment by AndrzejKaczynski** [comment]
Amazing!!

Have a nice weekend as well :)

**Comment by thomas-stockx** [comment]
@AndrzejKaczynski New version is up on Pub, thanks!

**Comment by AndrzejKaczynski** [comment]
@thomas-stockx Thank you as well!

**Pull request merged**
